Repository OpenScienceRoadmap/jrost, pull requests merged in 2018-08, with the labels that each got.

#9 add Open Engineering to participating organizations
  JROSTOrganizations.csv
  JROSTPeople.csv
Labels: participants

#11 Update internal links to participants
  README.md
Labels: bug

#15 add a few missing orgs, left out a couple that are listed as projects…
  participants/JROSTOrganizations.csv
  registries/apis.csv
Labels: participants, registries
